UPDATE public.charge_box_info SET address_id = 1324 WHERE id = '"Kesh Palace" Hotel';
UPDATE public.charge_box_info SET address_id = 1326 WHERE id = '"Baraka" савдо комплекси';
UPDATE public.charge_box_info SET address_id = 1303 WHERE id = '"IDEAL GAZ" заправка';
UPDATE public.charge_box_info SET address_id = 1305 WHERE id = '"EDISON" ресторан';
UPDATE public.charge_box_info SET address_id = 1301 WHERE id = 'TOK BOR ULTRA 200 кВт';
UPDATE public.charge_box_info SET address_id = 1306 WHERE id = '"Qo''ng''irod Soda" завод';
UPDATE public.charge_box_info SET address_id = 1308 WHERE id = '"Gavhar" ресторан';
UPDATE public.charge_box_info SET address_id = 1307 WHERE id = 'Urgench';
UPDATE public.charge_box_info SET address_id = 1309 WHERE id = '"Sarimoy" чойхона';
UPDATE public.charge_box_info SET address_id = 1311 WHERE id = 'Buxoro savdo majmuasi';
UPDATE public.charge_box_info SET address_id = 1312 WHERE id = 'Учкудук';
UPDATE public.charge_box_info SET address_id = 1313 WHERE id = '"Gold Plaza" Hotel';
UPDATE public.charge_box_info SET address_id = 1310 WHERE id = '"Nozimbar" кафе';
UPDATE public.charge_box_info SET address_id = 1314 WHERE id = '"REGAL" Hotel';
UPDATE public.charge_box_info SET address_id = 1315 WHERE id = '"Best oil" заправка';
UPDATE public.charge_box_info SET address_id = 1316 WHERE id = '"Family Park" савдо комплекси';
UPDATE public.charge_box_info SET address_id = 1317 WHERE id = '"Gold Sogdiana" Hotel';
UPDATE public.charge_box_info SET address_id = 1318 WHERE id = '"UNG" Petro';
UPDATE public.charge_box_info SET address_id = 1319 WHERE id = '"Alexander" Hotel';
UPDATE public.charge_box_info SET address_id = 1320 WHERE id = '"Hilton Garden Inn" Hotel';
UPDATE public.charge_box_info SET address_id = 1321 WHERE id = '"Marokand SPA" Hotel';
UPDATE public.charge_box_info SET address_id = 1323 WHERE id = '"KAMOL" заправка';
UPDATE public.charge_box_info SET address_id = 1329 WHERE id = '"Anhor" кафе';
UPDATE public.charge_box_info SET address_id = 1331 WHERE id = '"KARVON" кафе';
UPDATE public.charge_box_info SET address_id = 1332 WHERE id = '"NABIXON OTA" кафе';
UPDATE public.charge_box_info SET address_id = 1327 WHERE id = '"Termez Palace" Hotel';
UPDATE public.charge_box_info SET address_id = 1325 WHERE id = '"Diydor" кафе';
UPDATE public.charge_box_info SET address_id = 1330 WHERE id = '"Масжид" Охангарон';
UPDATE public.charge_box_info SET address_id = 1328 WHERE id = '"UNG" Petro (Жиззах)';
UPDATE public.charge_box_info SET address_id = 1552 WHERE id = '"Tatneft" заправка';
UPDATE public.charge_box_info SET address_id = 1553 WHERE id = '"Yelkan" ресторан';
UPDATE public.charge_box_info SET address_id = 1551 WHERE id = 'Ichan Kala';
UPDATE public.charge_box_info SET address_id = 1555 WHERE id = '"Global Gas" заправка';
UPDATE public.charge_box_info SET address_id = 1556 WHERE id = '"Qasr" Hotel';
UPDATE public.charge_box_info SET address_id = 1557 WHERE id = '"Makro" Қўқон';
UPDATE public.charge_box_info SET address_id = 1558 WHERE id = '"OYDIN PLAZA" Hotel';
UPDATE public.charge_box_info SET address_id = 1559 WHERE id = 'Shodlik';
UPDATE public.charge_box_info SET address_id = 1560 WHERE id = '"Korzinka" супермаркет Наманган';
UPDATE public.charge_box_info SET address_id = 1561 WHERE id = '"FERGANA" Hotel';
UPDATE public.charge_box_info SET address_id = 1562 WHERE id = '"Grand Fergana" Hotel';
UPDATE public.charge_box_info SET address_id = 1563 WHERE id = '"Navruz" Bazzar';
UPDATE public.charge_box_info SET address_id = 1564 WHERE id = '"O''zbegim" Trade Center';
UPDATE public.charge_box_info SET address_id = 1565 WHERE id = '"Makro" супермаркет Андижон';
UPDATE public.charge_box_info SET address_id = 1554 WHERE id = '"Kamtar" кафе';
UPDATE public.charge_box_info SET address_id = 1566 WHERE id = '"Asmald Palace" Hotel';
UPDATE public.charge_box_info SET address_id = 1567 WHERE id = '"impex Gas Service" заправка';
UPDATE public.charge_box_info SET address_id = 1701 WHERE id = '"Compass Mall" савдо комплекси';
UPDATE public.charge_box_info SET address_id = 1702 WHERE id = 'IT Park 1';
UPDATE public.charge_box_info SET address_id = 1702 WHERE id = 'IT Park 2';
UPDATE public.charge_box_info SET address_id = 1704 WHERE id = '"Mercury" Бизнес центр';
UPDATE public.charge_box_info SET address_id = 1705 WHERE id = '"Mirobod" бозори';
UPDATE public.charge_box_info SET address_id = 1706 WHERE id = 'Экология вазирлиги';
UPDATE public.charge_box_info SET address_id = 1707 WHERE id = '"Tatneft" заправка. Тошкент';
UPDATE public.charge_box_info SET address_id = 1710 WHERE id = '"Megawatt" автосалон';
UPDATE public.charge_box_info SET address_id = 1710 WHERE id = '"Megawatt" автосалон 2';
UPDATE public.charge_box_info SET address_id = 1711 WHERE id = '"Chekhov Yulduz" финтес центр';
UPDATE public.charge_box_info SET address_id = 1712 WHERE id = '"Simurg" Бизнес центр';
UPDATE public.charge_box_info SET address_id = 1714 WHERE id = '"Megawatt" Когон';
UPDATE public.charge_box_info SET address_id = 1708 WHERE id = '"Samarqand Darvoza" савдо маркази';
UPDATE public.charge_box_info SET address_id = 1713 WHERE id = '"Megawatt" автосервис';
UPDATE public.charge_box_info SET address_id = 1709 WHERE id = 'Real Tex';
UPDATE public.charge_box_info SET address_id = 1703 WHERE id = 'Tashkent INDEX';
